version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: wutmeme-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: wutmeme
      POSTGRES_USER: wutmeme_user
      POSTGRES_PASSWORD: wutmeme_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: wutmeme-backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    working_dir: /app
    volumes:
      - ./backend:/app
    command: npm run start:dev

  frontend:
    build:
      context: ./frontend
    container_name: wutmeme-frontend
    restart: unless-stopped
    ports:
      - "5173:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
      
volumes:
  pgdata:
